server:
  port: 8081
spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:postgresql://localhost:5432/example_spring_boot_2
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/my-keycloak