server:
  port: 8081
spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:postgresql://localhost:5432/testabc
    username: postgres
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/my-keycloak